### ISSUE TITLE
Open an apk encounters error

### ISSUE THREAD

**Issue by HONEY-SUNMX** [Surendrajat/APKLab#20]
Platform: Ubuntu18
When i click the "APKLab: Open an APK", it will still download the apktool.jar and signer.jar although i have already done that. And when download completed, it popups the choose surface so i can choose which apk file to decode , but the decode result is failed. And when i try to decode the apk file by the execute the apk.jar manually, it's ok.

**Comment by Surendrajat** [comment]
@HONEY-SUNMX Could you please paste the output logs from console here?

**Comment by Surendrajat** [comment]
Seems like duplicate of #24
