### ISSUE TITLE
Jar getting downloaded, yet not used in the final command line.

### ISSUE THREAD

**Issue by N0fix** [Surendrajat/APKLab#24]
**The bug**
Upon executing any command, the jar path file (either apktool or uber signer) isn't getting used in the command line, e.g:

```
java -jar d <path/to/my/apk>
```
The path of the jar is missing, although the extension downloads it. I hardcoded a correct path in the extension settings, without success. 

**Expected behavior**
The extension should not re-download the jar files at every command, and should be using them in the final command lines e.g:
```
java -jar <path/to/apktool> d <path/to/my/apk>
```

**Console Logs**
<details>

Rebuilding myapk.apk into extracted_apk/dist/...
----------------------------------------------------------------
java -jar  b /home/user/Downloads/apk/extracted_apk --use-aapt2
Error: Unable to access jarfile

</details>

**System Information:**
 - OS: Ubuntu 18.04.1
 - VSCode Version: 1.48.1

**Comment by Surendrajat** [comment]
@N0fix Can you provide the logs when it's downloading jar files too?

**Comment by N0fix** [comment]
Sorry for this stupid issue, restarting the editor made it work.

**Comment by Surendrajat** [comment]
@N0fix This seems like a legit issue :)
Maybe it should reload the editor window itself after the update.
