### ISSUE TITLE
no main manifest attribute, in /usr/share/apktool/apktool.jar

### ISSUE THREAD

**Issue by rypz79** [Surendrajat/APKLab#28]
**Describe the bug**
Cannot decompile APK

**To Reproduce**
1. Edited the absolute path to  Apk Signer, Apktool, Jadx settings.json looks as follows:
``` {
    "python.pythonPath": "/usr/bin/python3",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "workbench.iconTheme": "vscode-icons",
    "C_Cpp.updateChannel": "Insiders",
    "python.languageServer": "Microsoft",
    "window.zoomLevel": 1,
    "apklab.apkSignerPath": "/lib/android-sdk/build-tools/debian/apksigner.jar",
    "apklab.jadxDirPath": "/home/roey/jadx/build/jadx/bin/jadx",
    "apklab.apktoolPath": "/usr/share/apktool/apktool.jar"
}
```
2. Click on:
CTRL+SHIFT+P -> APKLab: open an APK -> Select APK (/home/roey/ApkProjects/ynet_6.78.apk) ->
Check decompile_java [Use Jadx] -> Press OK

3. See error:
> Decoding ynet_6.78-MOD.apk into /home/roey/ApkProjects/ynet_6.78-MOD...
> java -jar /usr/share/apktool/apktool.jar d /home/roey/ApkProjects/ynet_6.78-MOD.apk -o /home/roey/ApkProjects/ynet_6.78-MOD
> no main manifest attribute, in /usr/share/apktool/apktool.jar
> Decoding process exited with code 1

**Expected behavior**
A VScode window with decompiled (to smali) APK

**Console Logs**
<details>

Please paste all your console output here... between the details HTML tags!

</details>

**System Information:**
 - OS: Kububntu 20.10 x64
 - VSCode Version: 1.50.1

**Additional context**

**Comment by Surendrajat** [comment]
Seems like a corrupted apktool.jar file. Try to remove the path and let it download the latest apktool.
Also, the apksigner used in APKLab is [uber-apk-signer](https://github.com/patrickfav/uber-apk-signer).

**Comment by rypz79** [comment]
> Seems like a corrupted apktool.jar file. Try to remove the path and let it download the latest apktool.
> Also, the apksigner used in APKLab is [uber-apk-signer](https://github.com/patrickfav/uber-apk-signer).

Now I get this error
```Downloading file: apktool_2.4.1.jar
Download size: 16.84 MB
Downloaded 1%
Downloaded 2%
Downloaded 3%
...
Downloaded 100%
Downloading file: uber-apk-signer-1.1.0.jar
Download size: 1.78 MB
Downloaded 1%
Downloaded 2%
Downloaded 3%
...
Downloaded 100%
Downloading file: jadx-1.1.0.zip
Download size: 14.32 MB
Downloaded 1%
Downloaded 2%
Downloaded 3%
...
Downloaded 100%
Extracted /home/roey/.apklab/jadx-1.1.0.zip into /home/roey/.apklab/jadx-1.1.0
Decoding ynet_6.79.apk into /home/roey/ApkProjects/ynet_6.79
java -jar  d /home/roey/ApkProjects/ynet_6.79.apk -o /home/roey/ApkProjects/ynet_6.79
Error: Unable to access jarfile
Decoding process exited with code 1```
Why he doesn't cache those files and needs to re-download them everytime?
