### ISSUE TITLE
Tools (apktool, jadx, uber-sign-apk) path are not identified during a test on an APK

### ISSUE THREAD

**Issue by Shosta** [Surendrajat/APKLab#30]
**Describe the bug**
When I am developing in a Remote Container, apktool, jadx or uber-sign-apk are not found while extracting the apk

**To Reproduce**
1. Launch VSCode in a remote container (base: ubuntu for isntance)
2. Required Add-ons are installed automatically through the vscode/.devcontainer file
2. The apk to test is on the folder from where I launched the Remote Container
3. Launch the ApkLab add-on
4. java -jar  d /workspaces/ApkLab-VSCode/InsecureBankv2.apk -o /workspaces/ApkLab-VSCode/InsecureBankv2
apktool.jar is not found.
In the add-on settings the Remote (devcontainer) and Worksapce, the path to the tools are properly identified.
In the filesystem, apktool.jar and uber-sign-apk.jar are executable (chmod +x).

**Expected behavior**
Just want the apktool to be found so that the apk can be decompiled.

**Console Logs**
```
Extracted /root/.apklab/jadx-1.1.0.zip into /root/.apklab/jadx-1.1.0
-------------------------------------------------------------------------
Decoding InsecureBankv2.apk into /workspaces/ApkLab-VSCode/InsecureBankv2
-------------------------------------------------------------------------
java -jar  d /workspaces/ApkLab-VSCode/InsecureBankv2.apk -o /workspaces/ApkLab-VSCode/InsecureBankv2
Error: Unable to access jarfile
Decoding process exited with code 1
```

Please paste all your console output here... between the details HTML tags!

</details>

**System Information:**
 - OS: Ubuntu 20.04
 - VSCode Version: 1.50.1
- VSCode Add-on : 
    * [Docker](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker)
    * [Remote Container](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers)

**Additional context**
Working in a remote container.
Here is the Dockerfile I am using  :
```
FROM ubuntu:20.04 as ubuntu-downloader

ENV HACKTOOLS_DIR=/home/Developpement/HackingTools

WORKDIR $HACKTOOLS_DIR

# Install adb tools, unzip, wget, signapk and apktool
RUN apt update -y && apt install -y  --no-install-recommends \
    wget \
    unzip

# Download apktool-2 & Rename downloaded jar to apktool.jar
RUN mkdir -p /home/Developpement/HackingTools/ApkTool && \
    wget --no-check-certificate --quiet -O /home/Developpement/HackingTools/ApkTool/apktool https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool && \
    wget --no-check-certificate --quiet -O /home/Developpement/HackingTools/ApkTool/apktool.jar https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.4.1.jar



# Pull Ubuntu LTS image.
FROM ubuntu:20.04

# Labels and Credits
LABEL \
    name="Apk Lab Env" \
    author="Rémi Lavedrine <remi@github.com>" \
    maintainer="Rémi Lavedrine <remi@github.com>" \
    description="Android Security Test (AndroSecTest) is an automated, all-in-one mobile application (Android) security assessment framework capable of performing static."

ENV SRC_DIR=/root/home/apkLab-Results
ENV HACKTOOLS_DIR=/home/Developpement/HackingTools
WORKDIR $SRC_DIR

# Set up the time as Europe/Paris
ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone


# Install adb tools, unzip, wget, signapk and apktool
RUN apt update -y && apt install -y --no-install-recommends \
    openjdk-8-jdk \
    usbutils \
    unzip \
    wget \
    android-tools-adb \
    bash-completion \
    golang-go \
    gcc


# Download apktool-2 & Rename downloaded jar to apktool.jar
RUN wget --no-check-certificate --quiet -O /usr/local/bin/apktool https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool && \
    wget --no-check-certificate --quiet -O /usr/local/bin/apktool.jar https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.4.1.jar && \
    chmod +x /usr/local/bin/apktool && \
    chmod +x /usr/local/bin/apktool.jar


# Install zsh as the default shell within the container.
RUN apt install -y --no-install-recommends git zsh && chsh -s /usr/bin/zsh

RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.1/zsh-in-docker.sh)" -- \
    -t https://github.com/denysdovhan/spaceship-prompt \
    -a 'SPACESHIP_PROMPT_ADD_NEWLINE="false"' \
    -a 'SPACESHIP_PROMPT_SEPARATE_LINE="false"' \
    -p git \
    -p sudo \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions

```

**Comment by Surendrajat** [comment]
@Shosta Thanks for the detailed issue. This seems to be a [known issue](https://github.com/Surendrajat/APKLab#known-issues). So when you run APKLab for the first time, it will download apktool, uber-apk-signer and jadx, and update their paths in settings. However, the settings are not picked by extension after that without restarting VS Code.
This is the line which updates the config and I suspect is problematic. You're welcome to find a fix for this.
https://github.com/Surendrajat/APKLab/blob/93f927e10e1232e544f61fdc7725a5958d8f9cfd/src/downloader.ts#L135

**Comment by Shosta** [comment]
Thanks for pointing this out. 👌🏼

I am pretty noob at VSCode extension development but I'll try to do something. 👍🏼
I'll love to have a Docker image that has all 3 required tools and the VSCode extension APKLab points directly to the proper location.

**Comment by Surendrajat** [comment]
@Shosta It's easy to build a docker image with the tools actually. Just copy the tools somewhere in the container and append the paths to VS Code settings file in `$HOME/.config/Code/User/settings.json` as a startup script or just replace it with your `settings.json` altogether.

**Comment by Shosta** [comment]
Yes, planing to do that. 👍🏼

**Comment by Surendrajat** [comment]
@Shosta I will leave it open until some fix for this issue is found.

**Comment by Shosta** [comment]
Yes. Thank you. 
I'll try to do it tonight.

**Comment by Shosta** [comment]
I opened a Pull Request. https://github.com/Surendrajat/APKLab/pull/32
Ask anything if you don't know how to use it (I made it as straightforward as I could).

Moreover, I can push the Image to my Docker Hub repository so that users can download it through a `Docker pull` command and then attach a running container in the "Remote Container" extension.

**Comment by Surendrajat** [comment]
@Shosta I've closed this one as I think it has been fixed with linked PR. Please try this once the new version is released and confirm if APKLab automatically downloads dependencies for you.
