### ISSUE TITLE
Add apk-mitm patch

### ISSUE THREAD

**Issue by Surendrajat** [Surendrajat/APKLab#37]
**Is your feature request related to a problem? Please describe.**
No problem. Just a new feature.

**Describe the solution you'd like**
Provide an option to apply [apk-mitm](https://github.com/shroudedcode/apk-mitm/) patch once the APK is opened.

**Describe alternatives you've considered**
Install apk-mitm and let it do the job.

**Additional context**
Since APKLab has all the tools needed(Apktool, uber-apk-signer, etc.) and ApkTool will have ability to make an APK debuggable too. So less work overall.

**Comment by shroudedcode** [comment]
apk-mitm maintainer here! :wave: I saw you starred my repository and found APKLab through that. I haven't tried it yet, but it looks very promising and I will definitely give it a try in my next Android reverse engineering effort. If you need me to make any changes (like adding an option to path APKs that have already been decoded into a directory, etc.), don't hesitate to let me know! :smiley:

**Comment by Surendrajat** [comment]
Hi @shroudedcode. Thanks for the cool project. I found it through GH recommendations :)

Man, I'd have loved to see that option in apk-mitm but with a little discussion(thinking of not bothering you right away ;), we agreed to ship all the patching logic from apk-mitm in APKLab itself(and an extended LICENSE file too), and as you can see my friend @amsharma44 has already started work to port it over to APKLab in https://github.com/Surendrajat/APKLab/tree/feature/apk-mitm branch.

However, we hit a roadblock on windows with posix path being ignored and `LF` in regex not working with `CRLF`. Is that something only we are facing? or apk-mitm has the same issue? Once we fix it we are planning to open a PR in apk-mitm as well.

**Comment by Surendrajat** [comment]
Hi @shroudedcode. Thanks for the cool project. I found it through GH recommendations :)

Man, I'd have loved to see that option in apk-mitm but with a little discussion(thinking of not bothering you right away ;), we agreed to ship all the patching logic from apk-mitm in APKLab itself(and an extended LICENSE file too), and as you can see my friend @amsharma44 has already started work to port it over to APKLab in https://github.com/Surendrajat/APKLab/tree/feature/apk-mitm branch.

However, we hit a roadblock on windows with posix path being ignored and `LF` in regex not working with `CRLF`. Is that something only we are facing? or apk-mitm has the same issue? Once we fix it we are planning to open a PR in apk-mitm as well.

**Comment by shroudedcode** [comment]
> we agreed to ship all the patching logic from apk-mitm in APKLab itself(and an extended LICENSE file too), [...]. Hope that's okay

That's fine with me! Maybe you could also add add some credit to the top of the `mitm-tools.ts` file. This is less about licensing and more about making it easier for people source-diving to see the where that code originally came from:

```ts
// MITM patching code adapted from:
// https://github.com/shroudedcode/apk-mitm
```

> However, we hit a roadblock on windows with posix path being ignored and `LF` in regex not working with `CRLF`.

Can you clarify in which cases these two things become an issue? Which paths are being ignored and which regex patterns are affected by this?

**Comment by Surendrajat** [comment]
> Maybe you could also add add some credit to the top of the mitm-tools.ts file.

Even though I'm planning to link it in the description and credit section in README, this is also a good idea.

> Can you clarify in which cases these two things become an issue? ...

It's when we tested it out on windows it detects all files but can't replace the fn. See if https://github.com/Surendrajat/APKLab/commit/fd9dc9b4b349cb4531a3f0dc5928f5031334d101 makes some sense to you. CC @amsharma44

**Comment by amsharma44** [comment]
Hi @shroudedcode 

Please take a look at different result on Windows with same apk file.

![apk-mitm Windows vs Linux](https://user-images.githubusercontent.com/16615516/102081792-cd647100-3e36-11eb-933b-6e5f670d25ba.png)

There are two issues with current apk-mitm running in Windows.

1. Glob pattern only support posix path i.e forward-slashes which is different from Windows path conventions, therefore it won't be able to find any .smali files in the directory.

`const smaliFiles = await globby(path.join(directoryPath, 'smali*/**/*.smali'))` 

2. `METHOD_PATTERNS` is derived from regex which matches Linux's new line character `LF` but if you decode an apk on Windows, it will have `CRLF` as new line character so the regex won't be able to find the match of method signatures.


CC @Surendrajat

**Comment by shroudedcode** [comment]
Thanks for the explanation, @amsharma44! I've opened [an issue on the `apk-mitm` repo](https://github.com/shroudedcode/apk-mitm/issues/27) about this.
