### ISSUE TITLE
Add quark engine as one of the analyzer.

### ISSUE THREAD

**Issue by 18z** [Surendrajat/APKLab#38]
**Is your feature request related to a problem? Please describe.**
Quark engine is a apk analyzer that can quicky tell users what this apk does. So we're thinking about integrating quark as one of the analyzers. Users can first use quark to have a quick look of the apk and then dive in the details with the features apklab provides.

Belows are features and reports released recently.
![FB_IMG_1607307398565](https://user-images.githubusercontent.com/593954/101302495-b346f380-3876-11eb-8e9a-8f32b2ccccb1.jpg)
![FB_IMG_1607307392829](https://user-images.githubusercontent.com/593954/101302505-bb069800-3876-11eb-9c3d-d85dbd145fff.jpg)
![FB_IMG_1607307385159](https://user-images.githubusercontent.com/593954/101302513-bfcb4c00-3876-11eb-987d-ec8b0f288f0b.jpg)

**Comment by krnick** [comment]
our Github repository is here: https://github.com/quark-engine/quark-engine 😄

**Comment by Surendrajat** [comment]
@18z @krnick Quark engine looks promising and I will be happy to integrate it into APKLab.
I've looked into the project page, docs, etc. and it seems to be a CLI frontend with preinstalled(or user-provided) rules to work on. Few initial observations:
- The main dependency here is quark and python. That can be listed along with other requirements. 
- For the main UI component I guess some sort of `APKLab: Malware analysis with Quark-Engine` followed by an APK selector and optional(?) rules selector.
- The output is to come in VS Code output channel window(?).
- Some other useful features might need a separate UI component(?).

Let me know if I got it right and this flow works for you. We can discuss more in detail the points above or the ones that I missed.

CC @amsharma44

**Comment by 18z** [comment]
Hi @Surendrajat 

Thanks for replying us. 
I'll answer your questions below with bullet points.

-  Question: It seems to be a CLI frontend with preinstalled(or user-provided) rules to work on. 
    - Yes! BTW, users can use command ```freshquark``` to get newest rules we provide or they can use rules written by themselves.

- Question: The main dependency here is quark and python. That can be listed along with other requirements.
    - YES

- Question: For the main UI component I guess some sort of APKLab: Malware analysis with Quark-Engine followed by an APK selector and optional(?) rules selector.
    - I agree with the idea of rules selector. But I suggest to refine this to ```rule type``` selector since we're now managing rules with labels. This is our rule viewer UI. https://bit.ly/36KlxGL

- Question: The output is to come in VS Code output channel window(?).
    - Ideally, we're thinking the output (adjusted summary report) is to come to the panel (Area D shown in the picture blow) . Once the user click on the detected behavior in area D. The editor groups (Area C) shows the exactly the decompiled source code or the smali code directly. 

<img width="775" alt="Screen Shot 2020-12-08 at 2 11 06 PM" src="https://user-images.githubusercontent.com/593954/101447049-6ab73500-395f-11eb-9dbf-3ca6a6046997.png">


- Question: Some other useful features might need a separate UI component(?).
    - YES! For example, call graphs, detailed reports and classification reports.

**Comment by Surendrajat** [comment]
@18z 
> But I suggest to refine this to rule type selector since we're now managing rules with labels.

Is there a list of labels shipped with quark? Or is it fixed? To show some multi-select quickpick one needs to know all the labels.

> Ideally, we're thinking the output (adjusted summary report) is to come to the panel (Area D shown in the picture blow).

Yeah. That's what I mean by output Channel. There's an output tab in panel D where each extension has it's own channel.

> Once the user click on the detected behavior in area D. The editor groups (Area C) shows the exactly the decompiled source code or the smali code directly.

This will require most of the work I guess. Is it possible to print the smali file name in quark analysis? Hitting the exact file in java source will get a bit tricky as well due to anonymous classes (`*$1.smali` etc.). Let's think this through.

**Comment by 18z** [comment]
@Surendrajat 

> Is there a list of labels shipped with quark? Or is it fixed? To show some multi-select quickpick one needs to know all the labels.

Labels are written in the detection rules and many more will be shipped with quark. 

> This will require most of the work I guess. Is it possible to print the smali file name in quark analysis? Hitting the exact file in java source will get a bit tricky as well due to anonymous classes (*$1.smali etc.). Let's think this through.

Yes! We can print the smali file name in quark analysis.
We did some experiments and find out that the most comprehensive information of the source code is written in file names like a.smali not the ones with numbers (a.2.smali etc).
If what we found is right, then we can ignore the anonymous classes.

**Comment by pulorsok** [comment]
Hi, @Surendrajat, I am also a member of Quark-Engine. 
From now on, I will take care of this issue and working on the integration.

**Comment by Surendrajat** [comment]
Hi @pulorsok. Glad to know that.
Meanwhile, we have been working to make APKLab more contributor-friendly by adding linting and formatting rules, and basic integration tests. I'll add a contributing guide sometime soon as well.
Hope it will make things easy for you. Please feel free to ask anything related here or on telegram.

**Comment by Surendrajat** [comment]
@18z 
> Labels are written in the detection rules and many more will be shipped with quark.

I hope there aren't too many rules to parse. It might be slower if these rules are in separate JSON files.
> Yes! We can print the smali file name in quark analysis.

Cool. I'm wondering if we can show it relative to the currently opened dir(decoded project root) as VSCode will automatically make it clickable.

> If what we found is right, then we can ignore the anonymous classes.

Hope you're right. I am planning to implement a simple smali -> java file switcher and I think it should be fine for a start. The user will click on smali file link and then something like right-click -> show java source.
