### ISSUE TITLE
Open Apk error

### ISSUE THREAD

**Issue by berkayyildi** [Surendrajat/APKLab#41]
**Describe the bug**
Windows 10 Apk open bug

**To Reproduce**
1. ctrl + shift + p
2. Open an APK
3. See error

**Expected behavior**
Show the UI

**Console Logs**
Downloading file: apktool_2.4.1.jar
Error: Creating file
Can't download/update dependencies!

</details>

**System Information:**
 - Window 10
 - VSCode Version: 1.52.1

**Comment by amsharma44** [comment]
Hi @berkayyildi, Can you please update your APK Lab extension to version 1.2.0 and share output logs.

**Comment by berkayyildi** [comment]
The new version 1.2.0 fixed the problem.
Thank you.
