### ISSUE TITLE
Initialize git repo in decoded project

### ISSUE THREAD

**Issue by Surendrajat** [Surendrajat/APKLab#85]
**Is your feature request related to a problem? Please describe.**
So when working on app modification it's very common that someone would want to initialize git in decoded project dir for easier tracking of changes.

**Describe the solution you'd like**
Therefore, let's add this feature to initialize git after decoding/decompiling and just before opening the new window using the below steps:
```bash
cd decodedDir
git init
git add -A
git commit -m "initial commit"
```
Also, it might be useful to expose this as a configuration option so users, who might not need it, can disable it.

**Describe alternatives you've considered**
Just decode and run the above commands manually.

**Additional context**
Suggested by @shroudedcode

**Comment by shroudedcode** [comment]
This feature should also create a `.gitignore` file like this:

```
/build
/dist
```
