### ISSUE TITLE
Properly handle paths with space in it

### ISSUE THREAD

**Issue by Surendrajat** [Surendrajat/APKLab#95]
**Describe the bug**
Any file/DIR path passed to `child_process` with a space in it, results into an error as it's interpreted as multiple different commands together.

**To Reproduce**

1. Rename an APK file, or it's parent DIR to include a space.
2. Open and try to decode using APKLab
3. See error

**Expected behavior**
It should not throw error and should work correctly.

**System Information:**

- OS: Ubuntu 18.04
- VS Code Version: 1.52.1

**Additional context**
The path should be passed to `child_process` escaped or some other workaround should be used to tell `child_process` to interpret the path as a single parameter.

**Comment by amsharma44** [comment]
Not an issue. Able to decode APK with spaces in file name and directory.

Environment tested:
| OS  | VS Code Version | JDK |
| ------------- | ------------- | ------------- |
| Ubuntu 20.04  | 1.52.1  | OpenJDK 11  |
| Windows 10 20H2  | 1.52.1  | OpenJDK 8 |

APKLab Output:
```
----------------------------------------------------------------------------
Decoding sm 2.apk into c:\Users\User\Desktop\apk-test\folder with space\sm 2
----------------------------------------------------------------------------
java -jar C:\Users\User\.apklab\apktool_2.5.0.jar d c:\Users\User\Desktop\apk-test\folder with space\sm 2.apk -o c:\Users\User\Desktop\apk-test\folder with space\sm 2 --only-main-classes
I: Using Apktool 2.5.0 on sm 2.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\User\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
Decoding process was successful
```
